Upgrade bufbuild/protobuf and connectrpc/connect[-web] packages
quickfeed/quickfeed pull request #1147
Opened 2024-10-25 11:15 UTC by JosteinLindhom

- **chore: change import paths from "bufbuild/{connect/connect-web}" to "connectrpc/{connect/connect-web}". Fixes #1144**
- **chore: update buf.gen.yaml to version 2 and modify plugin configuration**
- **chore: regenerate proto files with protoc-gen-es v2.2.0**
- **refactor: update ResponseClient to be compatible with v2**
- **refactor: rewrite overmind components to be compatible with updated proto types**
- **refactor: update mock function signature to accept multiple parameters**
- **refactor: make tests compatible with updated v2 proto types**
- **refactor: update components to be compatible with v2 proto types**
- **refactor: update Helpers.ts to use new protobuf functions and types**
- **refactor: update import path for quickfeed service**

2024-10-30 09:00 UTC, JosteinLindhom commented
Need to figure out how to omit the `patch` import in `types.proto` for code generated for the frontend.

I think we managed to do this previously with `--exclude-path patch`, but that no longer seems to work.
We can manually remove the imports generated in the `.ts` files, but I'd like for us to *not* have to do that.

![image](https://github.com/user-attachments/assets/bce6d1f7-6034-41c8-93f7-d4645c9c3ee3)

2025-03-21 11:02 UTC, meling commented
@JosteinLindhom Here is a possible solution to the problem:
```yaml
version: v2
plugins:
- remote: buf.build/bufbuild/es
  out: public/proto
  opt: target=ts
  include_imports: true
- remote: buf.build/bufbuild/connect-web
  out: public/proto
  opt: target=ts
  include_imports: true
```
(not sure if both `include_imports` are necessary...)

This will generate an unnecessary file, but at least it removes the compile errors due to the unnecessary import. The other option is to add a sed command to remove the unnecessary line:
```typescript
import { file_patch_go } from "../patch/go_pb";
```

2025-03-21 21:33 UTC, meling requested changes
Looks like there still needs some work to weed out a few more conversions and get rid of some compile issues (test not passing). Also two minor deepsource issues.

2025-03-21 21:33 UTC, meling commented on public/src/__tests__/updateEnrollment.test.tsx
> +                if (request.FetchMode?.case === "courseID") {
Two questions.
1. Can this be expressed more compactly with a switch case?
2. Are there other cases than the ones covered? Because all cases does the same: `enrollments.push(e)`.

2025-03-21 21:33 UTC, meling commented on public/package.json
> +    "@connectrpc/connect": "^2.0.0-rc.1",
Looks like there is now a released version of these;
- https://www.npmjs.com/package/@connectrpc/connect
- https://www.npmjs.com/package/@connectrpc/connect-web

2025-03-24 08:46 UTC, JosteinLindhom commented on public/src/__tests__/setup.jest.js
> +// on globalThis. This setup file fixes that issue for now.
Appears to still be necessary.
I mean [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis)

Without this setup we get this error:

```ts
Test suite failed to run

    TypeError: globalThis.TextEncoder is not a constructor

       6 | import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
       7 | import type { Timestamp } from "@bufbuild/protobuf/wkt";
    >  8 | import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
```

2025-03-24 09:56 UTC, JosteinLindhom commented on public/src/Helpers.ts
> +        if (group.$typeName === "qf.Group") {
Seems there is a `isMessage` function we can use:

```ts
if (isMessage(group, GroupSchema)) {
    ...
}
```

Note that the `$typeName` is constrained to only these values in this instance: 

```ts
$typeName: "qf.Group" | "qf.Enrollment"
```

Comparing it to any other string will give you an error, e.g:

```ts
if (group.$typeName === "hello")
// This comparison appears to be unintentional because the types '"qf.Group" | "qf.Enrollment"' and '"hello"' have no overlap.ts(2367)
```

2025-03-24 12:09 UTC, meling commented on public/src/components/Results.tsx
> +                if (owner.$typeName === "qf.Enrollment") {
@JosteinLindhom Can this also use `isMessage(owner, EnrollmentSchema)`? If so, you should do a search for `"qf."` or `$typeName ===` and check for other places where you could use it... I didn't comment on all cases where we do string-based comparisons.

2025-03-24 12:11 UTC, meling commented on public/src/client.ts
> +export function createResponseClient<T extends DescService>(service: T, transport: Transport, errorHandler: (payload?: { method: string; error: ConnectError; } | undefined) => void): ResponseClient<T
This was a very long line. Should we keep the formatting with one parameter per line as before?

2025-03-24 12:12 UTC, meling commented on public/src/client.ts
> +export function createUnaryFn<I extends DescMessage, O extends DescMessage>(transport: Transport, method: DescMethodUnary<I, O>, errorHandler: (payload?: { method: string; error: ConnectError; } | un
Long line here as well and below... Same as above.

2025-03-24 12:21 UTC, JosteinLindhom commented on public/src/__tests__/updateEnrollment.test.tsx
> +                if (request.FetchMode?.case === "courseID") {
Even better, it can be removed altogether!

We used to have to do `getCourse` and `getEnrollments` separately.
Following #1160 this is no longer the case, and only `getCourse` needs to be mocked here.

2025-03-24 12:22 UTC, JosteinLindhom commented on public/src/components/Results.tsx
> +                if (owner.$typeName === "qf.Enrollment") {
Yes, converted all instances of `$typeName ===` now.

2025-03-25 16:19 UTC, meling commented on Makefile
> +	@perl -i -ne "print unless /import\s*\{\s*file_patch_go\s*\}\s*from\s*[\"'].*patch\/go_pb[\"'];/" $(proto_ts)
@JosteinLindhom I keep forgetting that `sed` is not a great choice for cross-platform commands because macOS sed and GNU sed is interpreting the `-i` option differently. Does WSL have `perl` installed by default?

2025-03-27 08:48 UTC, merged