Improve data fetching for courses
quickfeed/quickfeed pull request #1160
Opened 2024-12-13 12:02 UTC by JosteinLindhom

- **fix: enrollment `TotalApproved` should only count submissions for an assignment once Fixes #1151**
- **feat: add CountApprovedSubmissions method to track unique approved submissions count**
- **refactor: remove unused numApproved function**
- **refactor: move TestCountApproved from web package to qf package**
- **refactor: remove withActivityDate parameter from CountApprovedSubmissions method at it is unnecessary**
- **feat: add isTeacher and courseStatus helpers for user role and status checks**
- **feat: add GetCourseByStatus method to fetch course with preloaded data based on enrollment status**
- **fix: GetCourse now simply returns the course with no preloaded data**
- **refactor: remove unnecessary parameter from GetCourse calls**
- **refactor: simplify getEnrollmentsWithActivity method by removing unnecessary logic and using GetCourseByStatus**
- **refactor: remove unnecessary isTeacher parameter from getEnrollmentsWithActivity method**
- **refactor: remove getEnrollmentsByCourse method and streamline GetEnrollments logic**
- **refactor: remove unnecessary preload parameter from GetCourse calls in multiple methods**
- **refactor: update GetCourse method to use GetCourseByStatus for improved course retrieval**
- **refactor: userGroup is now derived from enrollments**
- **refactor: replace getEnrollmentsByCourse with getCourseData for improved course data retrieval**
- **refactor: simplified `fetchUserData` such that it does not preemptively fetch *all* data**
- **refactor: update Groups component to use users instead of enrollments for member display**
- **feat: preload group users in getEnrollments.**
- **fix(tests): update tests to use getCourseData instead of the removed getEnrollmentsByCourse**

2025-01-10 19:02 UTC, JoachimTislov commented on web/quickfeed_service.go
> +	status := courseStatus(ctx, in.Msg.GetCourseID())
status initializing is unnecessary

Can write it directly: 

```
course, err := s.db.GetCourseByStatus(in.Msg.GetCourseID(), courseStatus(ctx, in.Msg.GetCourseID()))
```

2025-01-10 19:05 UTC, JoachimTislov commented on web/quickfeed_service.go
>  			return nil, connect.NewError(connect.CodeNotFound, errors.New("failed to get enrollments for course"))
courseID := in.Msg.GetCourseID()

Is not used inside the error handling
```
s.logger.Errorf("GetEnrollments failed: course %d: %v", in.Msg.GetCourseID(), err)
```

2025-01-10 19:18 UTC, JoachimTislov commented on web/courses.go
> +	return course.GetEnrollments(), nil
Update the getEnrollmentsWithActivity to getEnrollmentsWithActivityByCourse, minor change since enrollments are retrieved by course ID

2025-01-10 19:21 UTC, JoachimTislov commented on web/quickfeed_service.go
> +func (s *QuickFeedService) GetEnrollments(ctx context.Context, in *connect.Request[qf.EnrollmentRequest]) (*connect.Response[qf.Enrollments], error) {
Consider intializing following variables to reduce duplicate code:

```
msg := in.Msg
fetchMode := msg.GetFetchMode()
statuses := msg.GetStatuses()
```

2025-01-10 19:24 UTC, JoachimTislov commented on database/gormdb_course.go
> +func (db *GormDB) GetCourseByStatus(courseID uint64, status qf.Enrollment_UserStatus) (*qf.Course, error) {
Codecov wants tests for the new method - GetCourseByStatus

2025-01-10 19:26 UTC, JoachimTislov commented on public/src/overmind/actions.tsx
>          return
Consider alerting user about the error ?

2025-01-10 19:35 UTC, JoachimTislov commented on database/gormdb_course.go
> +func (db *GormDB) GetCourseByStatus(courseID uint64, status qf.Enrollment_UserStatus) (*qf.Course, error) {
Consider splitting up the Method to make it more readable, for example one for handling the status (switch statement) and one for handling the case where the status is equal to "enrollment teacher".

Why not include this logic in the switch statement:
```
if status == qf.Enrollment_TEACHER {
		// Set number of remaining slip days for each course enrollment
		for _, e := range course.Enrollments {
			e.SetSlipDays(&course)
		}
		for _, g := range course.Groups {
			// Set number of remaining slip days for each group enrollment
			for _, e := range g.Enrollments {
				e.SetSlipDays(&course)
			}
		}
	}
```

2025-01-10 19:40 UTC, JoachimTislov commented on public/src/overmind/actions.tsx
>          return
I don't know if alerting the user about errors is common, but is the error handled in the backend, so the user doesn't need to know about it?

2025-01-10 19:49 UTC, JoachimTislov requested changes
I think everything looks good apart from what I commented on, and just add tests for what codecov complains about, fix Jest Test as well as Deep source and it should be good. This closes #1165 when merged into main

2025-01-14 07:55 UTC, meling requested changes
Some more nitpicks and stuff

2025-01-14 07:55 UTC, meling commented on database/gormdb_course.go
> +	switch status {
This method needs tests that cover the different status inputs. See the coverage complaints below.

2025-01-14 07:55 UTC, meling commented on database/gormdb_course.go
> +func (db *GormDB) GetCourseByStatus(courseID uint64, status qf.Enrollment_UserStatus) (*qf.Course, error) {
I don't think logic above can be moved into the switch statement since it depends on the results from this query:
```go
if err := m.First(&course, courseID).Error; err != nil {
```

2025-01-14 07:55 UTC, meling commented on web/courses_test.go
> +	if diff := cmp.Diff(pendingUserEnrollment, pendingCourseEnrollment, cmp.Options{
You don't need the `cmp.Options{}` thing; this works fine too since `Diff` takes a variadic argument...
```go
	if diff := cmp.Diff(pendingUserEnrollment, pendingCourseEnrollment,
		protocmp.Transform(),
		protocmp.IgnoreFields(&qf.Enrollment{}, "course"),
	); diff != "" {
```

2025-01-14 07:55 UTC, meling commented on web/quickfeed_service.go
> +	status := courseStatus(ctx, in.Msg.GetCourseID())
I find it more clear to create a `status` variable first.

2025-01-14 07:55 UTC, meling commented on web/quickfeed_service.go
> +func (s *QuickFeedService) GetEnrollments(ctx context.Context, in *connect.Request[qf.EnrollmentRequest]) (*connect.Response[qf.Enrollments], error) {
Agree on this.

2025-01-14 07:55 UTC, meling commented on web/quickfeed_service.go
> +		courseID := in.Msg.GetCourseID()
We should do `userID := in.Msg.GetUserID()` as well, but on Line 196.

2025-01-14 10:07 UTC, JosteinLindhom commented on database/gormdb_course.go
> +func (db *GormDB) GetCourseByStatus(courseID uint64, status qf.Enrollment_UserStatus) (*qf.Course, error) {
We can create a method on `Course` that populates enrollment slipdays, e.g.:

```go
// PopulateSlipDays populates the slip days for all enrollments in the course.
func (course *Course) PopulateSlipDays() {
	for _, enrollment := range course.GetEnrollments() {
		enrollment.SetSlipDays(course)
	}
	for _, group := range course.GetGroups() {
		for _, enrollment := range group.GetEnrollments() {
			enrollment.SetSlipDays(course)
		}
	}
}
```

Which we can use:

```go
	...
	if status == qf.Enrollment_TEACHER {
		course.PopulateSlipDays()
	}
	return &course, nil
```

2025-01-14 14:52 UTC, meling approved these changes

2025-01-14 15:32 UTC, merged