Added testing for the parsing of the criteria.json file, and checks for if the course Id is set correctly
quickfeed/quickfeed pull request #1164
Opened 2024-12-26 16:56 UTC by JoachimTislov

This PR is related to issue #729

2025-01-03 10:43 UTC, JosteinLindhom commented on assignments/testdata/tests/lab4/criteria.json
> +        "CourseID": 0,
To best match how we use the `criteria.json` file "in the wild" you could omit the `CourseID` here (and below on line 6).

Example of how a teacher would create `criteria.json` (no course ID):

```json
[
    {
        "heading": "Assignment 1",
        "criteria": [
            {
                "description": "Links work"
            },
            {
                "description": "Images are links, opening in a new tab"
            }
        ]
    }
]
```

The minimal `criteria.json` file we could use in this test is

```json
[
    {
        "criteria": [
            {}
        ]
    }
]
```

2025-01-06 15:42 UTC, meling requested changes
See comments inline.

2025-01-06 15:42 UTC, meling commented on assignments/testdata/tests/lab4/criteria.json
> +        "CourseID": 0,
@JoachimTislov I suggest to add more `criteria.json` example files to test different legal versions. You may need to add more `labX` folders to `testdata/tests/`... since you cannot have multiple `criteria.json` files per lab.

Also, you may consider adding an invalid `criteria.json` file to check that bad files give an expected parse error, but I think it is enough to provide one example.

2025-01-06 15:42 UTC, meling commented on assignments/testdata/tests/lab4/criteria.json
> +]
To avoid churn in commits, please use a newline at the end of files. Ask @JosteinLindhom how to fix this in VSCode. I think if you start VSCode with:
```sh
code quickfeed.code-workspace
```
It should be configured correctly, but not completely sure.

2025-01-10 16:27 UTC, JoachimTislov commented on assignments/testdata/tests/lab4/criteria.json
> +]
Yes, the quickfeed code workspace adds a newline 👍

2025-01-10 16:51 UTC, meling commented
@JoachimTislov Ping! This requires minor fixes to get merged.

2025-01-10 18:29 UTC, JoachimTislov commented
> @JoachimTislov Ping! This requires minor fixes to get merged.

Yes, I did the requested changes, PR currently fails since we reached the rate limit for Codecov

2025-01-10 18:51 UTC, meling requested changes

2025-01-10 18:51 UTC, meling commented on assignments/walk_tests_repo_test.go
> +func IsUnmarshalError(e error) bool {
It should not be an exported function.

2025-01-10 18:51 UTC, meling commented on assignments/walk_tests_repo_test.go
> +		if IsUnmarshalError(err) {
When will this happen? If this can happen, is it okay to not fail the test?

If there are `criteria.json` files that are expected to fail, then they should be tested separately (maybe in another test func) and checked that the error is the expected error.

2025-01-11 00:20 UTC, JoachimTislov commented on assignments/walk_tests_repo_test.go
> +		if IsUnmarshalError(err) {
I have to admit that this was a very cheap solution, considering the fact that there isn't an easy way to write proper testing for cases of an un-marshal error, because the "readTestsRepositoryContent" method only returns an error when it happens, no information about which lab it was. Therefore I added a check which allows for this to happen, specifically for lab 6 and 7, which is kind of pointless since you aren't really confirming the error...

I will try to find a proper way to test this.

2025-01-11 00:22 UTC, JoachimTislov commented on assignments/walk_tests_repo_test.go
> +func IsUnmarshalError(e error) bool {
Oh yeah, forgot about the uppercase part in Go

2025-01-11 00:35 UTC, JoachimTislov commented on assignments/walk_tests_repo_test.go
> +		if IsUnmarshalError(err) {
Nvm it only happes for lab 6 since the function returns the error and doesn't get to lab 7

2025-01-14 07:06 UTC, meling requested changes

2025-01-14 07:06 UTC, meling commented on assignments/walk_tests_repo_test.go
> +
Nit: No need for blank line here

2025-01-14 07:06 UTC, meling commented on assignments/walk_tests_repo_test.go
> +
Nit: No need for blank line here

2025-01-14 07:06 UTC, meling commented on assignments/walk_tests_repo_test.go
> +	checkLabWithInvalidCriteriaFile(t, invalidTypesFolder)
This should be written as a subtest:

```go
tests := []struct{
  name string
  folder string
}{
    {name: "NameOfSubTest", folder: inavlidTypesFolder},
   ...
}
for _, tc := range tests {
  t.Run(tc.name, func(t *testing.T) {
...
  })
}
```

2025-01-14 07:06 UTC, meling commented on assignments/walk_tests_repo_test.go
> +const invalidTypesFolder = "testdata/invalidJsonTests/invalidTypes"
Should be define inside the test function where they apply unless they are needed in the global package name space.

2025-01-14 16:04 UTC, meling commented
@JoachimTislov Ping! I requested a few more minor changes to this one.

2025-01-14 19:04 UTC, JoachimTislov commented
> @JoachimTislov Ping! I requested a few more minor changes to this one.

@meling Yes, i've pushed the requested changes

2025-01-14 20:01 UTC, meling approved these changes

2025-01-14 20:02 UTC, merged