ESLint Configuration
quickfeed/quickfeed pull request #693
Opened 2022-07-14 15:00 UTC by JosteinLindhom

2022-07-14 17:26 UTC, meling commented on public/.eslintrc.js
> +    ],
This line seems to have spaces, while all others use tab. When I save this file, this line changes those spaces to tab. Not sure what config is doing that though.

2022-07-15 05:36 UTC, meling requested changes
Check my suggestions!

2022-07-19 09:19 UTC, meling commented
I guess I've already reviewed this, but it is still in draft mode. More to be added to it?

2022-07-19 11:20 UTC, JosteinLindhom commented on public/.eslintrc.js
> +module.exports = {
It does for me as well. However, converting it to an ES module causes ESLint to stop working. Some solutions are mentioned [here](https://stackoverflow.com/questions/48624588/use-export-default-in-eslintrc-js-file-instead-of-module-exports), but none seem to be worth doing.

Alternatively we could simply rename `.eslintrc.js` -> `.eslintrc.json` and skip the `module.exports =` part entirely.

2022-07-22 14:10 UTC, meling approved these changes

2022-07-22 14:10 UTC, merged